### ISSUE TITLE
Example doesn't work! Can not callback any data!

### ISSUE THREAD

**Issue by goodspeed2011** [IndoorAtlas/unity-plugin#16] opened 2019-02-11 06:35 UTC
onLocationChanged,onStatusChanged,onHeadingChanged,onOrientationChange,onEnterRegion,onExitRegion these functions can not be callback, this example doesn't work! Could you please tell me how to calling component's callbacks immediatelly when start the app？i followed the instruction but it doesn't work!

**Comment by albrrt** [comment] 2019-04-12 16:26
Hi, did you find a solution ? I also cannot get it work...

**Comment by goodspeed2011** [comment] 2019-04-15 00:48
No, it doesn't work, i have given up. It's not like what IndoorAtlas said
at all.

albrt <notifications@github.com> 于2019年4月13日周六 上午1:26写道：

**Comment by simomar** [comment] 2019-04-17 09:38
Hello @goodspeed2011 @albrrt 

I couldn't reproduce the issue.

Please make sure that you are in an already mapped area when you are testing your Unity project. Otherwise those callbacks may not trigger. Also, please make sure that you have added correctly IndoorAtlas SDK credentials (API key and secret).

For further debugging I suggest you contacting IndoorAtlas [via our support site](https://support.indooratlas.com) so we can debug this issue further. I'm closing this issue but I'll comment again this thread if we find a way to reproduce the issue (with clear instructions).

**Closed by simomar** 2019-04-17 09:38 UTC
